FROM golang:alpine

WORKDIR /app

COPY . .

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

RUN go mod tidy

# RUN apk update && apk add --no-cache make

RUN go build -o main .

# COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

EXPOSE 8080

# CMD ["./main"]



